attributes = {
	'date_created': str,
	'last_updated': str,
	'first_name': str,
	'last_name': str,
	'username': str,
	'email': str,
	'bio': str,
	'liked_articles': [],
	'saved_articles': [],
	'liked_papers': [],
	'saved_papers': [],
	'search_history': [],
	'following': [],
	'rank': int}