attributes = {'title': str, 
'creation_date': str, 
'last_updated': str, 
'references': list, 
'content': str, 
'author': list, 
'tags': 'string', 
'num_saves': int, 
'saves': list, 
'num_likes': int, 
'likes': list, 
'num_citations': int, 
'citations': list, 
'content_type': int}
